sudo: false

language: rust

os:
- linux
- osx

rust:
- stable
- beta

install:
- rustc -Vv
- cargo -V

script:
- cargo build --verbose
- RUST_BACKTRACE=full cargo test --verbose -- --nocapture

cache:
  cargo: true
